stages:
  - build
  - build-noarch
  - deploy

.build-conda: &build-conda
  stage: build
  artifacts:
    paths:
      - dist/
  tags:
    - conda

build-linux:
  <<: *build-conda
  script:
    - conda build ./conda/camera --output-folder=dist/ --channel=http://bcu-ci.esrf.fr/stable
  tags:
    - cos7

build-win:
  <<: *build-conda
  script:
    - conda build ./conda/camera --output-folder=dist/ --channel=http://bcu-ci.esrf.fr/stable
  tags:
    - win

build-noarch:
  <<: *build-conda
  stage: build-noarch
  script:
    - conda build ./conda/tango --output-folder=dist/ -c tango-controls --channel=http://bcu-ci.esrf.fr/stable
  dependencies:
    - build-linux
    - build-win
  tags:
    - cos7

deploy-devel:
  stage: deploy
  environment:
    name: devel/$CI_COMMIT_REF_NAME
    url: http://bcu-ci.esrf.fr/devel
  dependencies:
    - build-linux
    - build-win
    - build-noarch
  script:
    - cp -Rf dist/* /conda-devel/
    - conda index /conda-devel/
  tags:
    - conda
    - linux
  only:
    - branches
  except:
    - stable
  when: manual

deploy-stable:
  stage: deploy
  environment:
    name: production
    url: http://bcu-ci.esrf.fr/stable
  dependencies:
    - build-linux
    - build-win
    - build-noarch
  script:
    - cp -Rf dist/* /conda/
    - conda index /conda/
  tags:
    - conda
    - linux
  only:
    - tags
    - stable
