# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}

package:
  name: lima-camera-basler
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - lima-sip6  13
    - lima-core 1.11*
    - pylon6-sdk
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('lima-sip6', min_pin='x.x.x', max_pin='x') }}
    - {{ pin_compatible('lima-core', min_pin='x.x', max_pin='x.x') }}
    - pylon6-sdk

test:
  requires:
    - cmake
  imports:
    - lima.basler
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
