{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: lima-camera-basler-tango
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python

requirements:
  run:
    - lima-tango-server
    - lima-camera-basler

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
